name:                cw-haskell
version:             0.1.0.0
github:              "richmanfx/cw-haskell"
license:             BSD3
author:              "Alexandr Jashchuk"
maintainer:          "r5am@mail.ru"
copyright:           "2022 Zoer R5AM"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/richmanfx/cw-haskell#readme>

dependencies:
- base >= 4.7 && < 5
- servant-server
- aeson
- wai
- warp
- servant
- http-media
- bytestring
- lucid

library:
  source-dirs: src

executables:
  cw-haskell-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cw-haskell

tests:
  cw-haskell-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - cw-haskell
